version: 2
updates:
  # Enable version updates for npm (Product Service)
  - package-ecosystem: "npm"
    directory: "/product-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "guyha" # Replace with your GitHub username
    assignees:
      - "guyha" # Replace with your GitHub username
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "product-service"

  # Enable version updates for npm (Web Frontend)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "guyha" # Replace with your GitHub username
    assignees:
      - "guyha" # Replace with your GitHub username
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "web-frontend"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/product-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 2
    reviewers:
      - "guyha" # Replace with your GitHub username
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 2
    reviewers:
      - "guyha" # Replace with your GitHub username
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 3
    reviewers:
      - "guyha" # Replace with your GitHub username
    commit-message:
      prefix: "chore(actions)"
    labels:
      - "dependencies"
      - "github-actions"
