version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - db
    environment:
      PORT: 4001
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/productdb"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: productdb

volumes:
  pgdata:
